-- Oracle schema for epsilon-resource-planner

CREATE TABLE people (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    role VARCHAR2(255) NOT NULL
);

CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    client_id NUMBER NOT NULL,
    CONSTRAINT fk_projects_client
        FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE assignments (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    person_id NUMBER NOT NULL,
    project_id NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    percentage NUMBER DEFAULT 100,
    CONSTRAINT fk_assignments_person
        FOREIGN KEY (person_id) REFERENCES people(id),
    CONSTRAINT fk_assignments_project
        FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX idx_assignments_person ON assignments(person_id);
CREATE INDEX idx_assignments_project ON assignments(project_id);
