-- PostgreSQL schema for epsilon-resource-planner

CREATE SCHEMA IF NOT EXISTS epsilon;
SET search_path TO epsilon;

CREATE TABLE people (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    client_id INTEGER NOT NULL,
    CONSTRAINT fk_projects_client
        FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    percentage NUMERIC DEFAULT 100,
    CONSTRAINT fk_assignments_person
        FOREIGN KEY (person_id) REFERENCES people(id),
    CONSTRAINT fk_assignments_project
        FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE INDEX idx_assignments_person ON assignments(person_id);
CREATE INDEX idx_assignments_project ON assignments(project_id);
